### ISSUE TITLE
Set up logging for all errors/exceptions

### ISSUE THREAD

**Issue by msmith533** [linted/Skip-Trace#9]
Keep an error log on disk rather than piping all error messages to stdout. This will allow for easier debugging, especially over longer periods of time. The error log needs to be timestamped, and a system for creating new and deleting old, no longer relevant log files needs to be created.

**Comment by linted** [comment]
would we only want the log file kept during the current execution? If so we could just open a file as write instead of append at the start of the program. That will over write anything that was originally there. After that we could do appends. Personally would prefer not to keep the file open during the duration of the program. The difference would be an open file for days, weeks, or possibly months on end, versus a large number of opens and writes. Of course we could limit the number of opens by opening the file when we get/send a request and closing when we finish with the request.

**Comment by msmith533** [comment]
Those are good questions. I've only worked with logging frameworks before, which abstract out all of those decisions. I'd like to research some common implementations.

**Comment by linted** [comment]
I found [This Library for python logging](https://docs.python.org/3/library/logging.html),  and this [HOW TO](https://docs.python.org/3.5/howto/logging.html) that shows how to set up file logging. I think it would be relatively trivial for us to implement this. thoughts?

**Comment by calebmckay** [comment]
Setting up a [logrotate](https://linux.die.net/man/8/logrotate) cron-job looks like exactly what you'd need. It can rotate out old log files each day/week or when they reach a certain size. If needed, you could add some user configuration for rotate frequency, though that may be overkill. As for adding the actual logging capability, looks like it'd be a piece of cake with that Python Logging library.

**Comment by linted** [comment]
I am not sure i want to start dealing with cron jobs if we don't have to, although that looks like an amazing feature. For now lets just swap out the print statements, and have the log file cleared on restart of the service. Any extra log features we can add to a new issue request.

**Comment by calebmckay** [comment]
I think I misread the article. You don't have to set up a whole cron job for it - there's already a /etc/cron.daily entry for logrotate, so you just have to add an entry to /etc/logrotate.d. [Here's an example](https://www.cyberciti.biz/tips/lighttpd-rotating-logs-with-logrotate.html). But I'm fine with putting that off until after the main logging is in place.

**Comment by calebmckay** [comment]
Functionality added in Pull Request #12, pending review.
